version = 0.1

[default]
[default.deploy]
[default.deployment.parameters]
stack_name = "order-processing-poc"
s3_prefix = "order-processing-poc"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []